- API/openapi.yaml
- DB/init/create_table.sh
- docker/.env.sample
> :seedling:  命名が別プロジェクトになっていたのを修正

- web/package.json
- web/src/App.js
- web/src/components/Navbar.js
- web/src/index.js
- web/yarn.lock
> chore: add navbar

- web/src/components/posts/PostCard.jsx
> 投稿カード作りました

- web/src/App.js
- web/src/components/Navbar.js
#4
サイドバー
フォント・アイコン・margin指定方法・各要素のclickイベント等に関して更なる変更が必要です。
> #4-サイドバーの実装

- web/src/App.js
- web/src/components/posts/PostCard.jsx
- web/src/pages/homePage.jsx
> homePageの土台作りました

- .vscode/settings.json
- web/src/components/Post.js
- web/src/pages/Timeline.js
#18
タイムラインページです。
marginやpadding等の修正をお願いします。
> chore: add timeline page component

- API/db.json
Co-authored-by: hihumikan <hihumikan@users.noreply.github.com>
> Json Server用Json作成

- web/package.json
- web/src/App.js
- web/src/components/Link.js
- web/src/components/Navbar.js
- web/src/index.js
- web/yarn.lock
> chore: install react-router-dom

- Backend/poetry.lock
- Backend/pyproject.toml
> add: poetry version file

- web/public/index.html
> chore: change page title

- web/package-lock.json
- web/package.json
- web/src/App.test.js
- web/src/components/Header.js
- web/src/pages/Timeline.js
- web/src/reportWebVitals.js
- web/src/setupTests.js
prettierのinstall(package.jsonの実装)
Homeのカードのhoverの実装
npm run format
> #25 creare post modal

- web/src/components/Button.js
> chore: create button component

- web/src/components/Button.js
- web/src/components/Header.js
- web/src/components/LoginModal.js
- web/src/components/MyInputGroup.js
- web/src/components/SignupModal.js
- web/src/pages/HomePage.js
> chore: update login and signup modal

- Backend/app.py
- Backend/controller/users.py
> blueprint化

- web/src/App.js
- web/src/index.js
close #22
`BrowserRouter` でラップする箇所を `index.js` から `App.js` に変更しました．
> refactor: move BrowserRouter from index.js to App.js

- web/src/components/Button.js
> chore: create button for modal

- web/src/components/LoginModal.js
- web/src/components/SignupModal.js
> modalに閉じるボタンを追加

- web/src/components/MyInputGroup.js
- web/src/components/SignupModal.js
> #58/feat select flag UI

- web/src/App.js
- web/src/pages/HomePage.js
- web/src/pages/Timeline.js
> homeのuserCardから適切に遷移されるように変更

- API/db.json
- web/package.json
- web/src/api/user.js
- web/src/components/Post.js
- web/src/pages/HomePage.js
- web/src/pages/Timeline.js
- web/yarn.lock
#61
`/timeline/:id` で該当するユーザの投稿を表示。
> #61-post-in-timeline

- web/src/components/LoginModal.js
- web/src/components/Navbar.js
- web/src/components/PostModal.js
- web/src/components/ProfileModal.js
- web/src/pages/HomePage.js
- web/src/pages/Timeline.js
> add post modal

- web/src/components/Navbar.js
> ロゴのfallbackを指定

- web/src/components/Navbar.js
> fix: display logo image correctly

- Backend/Dockerfile
- Backend/models/models.py
- docker/docker-compose-api.yml
- docker/docker-compose-db.yml
> fix: docker-compose間のネットワークを解消する

- .github/workflows/deploy.yml
> add: .github/workflows/deploy

- Backend/controller/posts.py
- Backend/controller/users.py
- Backend/models/models.py
> <feat>delete系追加

- Backend/controller/posts.py
- Backend/models/models.py
> <feat>postのPOSTを追加

- Backend/controller/users.py
- Backend/models/models.py
> #90: user patch

- Backend/controller/posts.py
- Backend/models/models.py
> <feat>postのDELETEを追加

- Backend/app.py
- Backend/controller/users.py
- Backend/poetry.lock
- Backend/pyproject.toml
- Backend/requirements.txt
> <fix>CORS修正

- .github/workflows/deploy.yml
> add: docker build

- Backend/controller/users.py
> <fix>json化(loginのみ) , 登録失敗時ステータスコード変更

- Backend/controller/users.py
> <fix>cookie

- API/db.json
- web/src/components/ChatBubble.js
- web/src/components/ChatInput.js
- web/src/pages/OnePostPage.js
> chore: fetch data into postpage

- web/src/components/ChatInput.js
- web/src/components/LoginModal.js
- web/src/components/MyInputGroup.js
- web/src/components/PostModal.js
- web/src/components/SignupModal.js
> chore: fix style (signup modal)

- web/src/api/post.js
- web/src/api/signup.js
- web/src/api/user.js
- web/src/components/ChatInput.js
- web/src/components/LoginModal.js
- web/src/pages/OnePostPage.js
- web/src/pages/Timeline.js
> chore: change endpoint from localhost

- Backend/models/models.py
> <fix>signup修正

- web/src/api/post.js
- web/src/api/signup.js
- web/src/components/ChatInput.js
> chore: add withCredentials

- Backend/models/models.py
> Session fix

- web/src/components/Header.js
- web/src/components/LoginModal.js
- web/src/components/Navbar.js
- web/src/context/AuthContext.js
- web/src/service/login.js
> ユーザの状態によってコンポーネントを切り替える

- web/src/components/LoginModal.js
> chore: fix path for userdata

- Backend/app.py
- Backend/models/models.py
> <fix>upload

- web/src/context/AuthContext.js
- web/src/pages/OnePostPage.js
- web/src/pages/Timeline.js
> ログイン状態に応じて投稿ボタンを切り替えるように
